ENG-5069 Sample application for working with multi file inputs/outputs
nextmv-io/community-apps pull request #39
Opened 2024-04-26 03:57 UTC by sebastian-quintero

# Description

Adds a new community app: `knapsack-ortools-csv` with an example fo how to read from `.input`, write to `.output` and print stats to `stdout`.

Aligns some whitespacing, missing type hints and minor formatting in other apps.

2024-04-26 14:14 UTC, merschformann commented on knapsack-ortools-csv/main.py
> +        reader = csv.DictReader(f, quoting=csv.QUOTE_NONNUMERIC)
These options are the pain of CSV. :sweat_smile: 
I think for this example its a great default though. :+1:

2024-04-26 14:47 UTC, merschformann approved these changes
Thanks for improving the type hinting! :hugs: 

There is a failing test btw.

Looks good otherwise! :heart:

2024-04-29 20:20 UTC, nmisek commented
noting here that we need to read from `input` and write to `output` without the `.`

2024-04-30 09:10 UTC, dirkschumacher requested changes

2024-04-30 09:10 UTC, dirkschumacher commented on knapsack-ortools-csv/README.md
> +`.input` folder, solves the problem, and writes the solution to an `.output`
`.input` or `input`?

2024-04-30 14:52 UTC, sebastian-quintero commented on knapsack-ortools-csv/README.md
> +`.input` folder, solves the problem, and writes the solution to an `.output`
Thank you

2024-04-30 14:56 UTC, dirkschumacher approved these changes

2024-04-30 15:02 UTC, merged